name: C++ CI

on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]

  jobs:
    build:
      runs-on: endeavouros
      steps:
        - uses: actions/checkout@v2
        - name: Compile C++
          run: g++ main.cpp -o main
